### PR TITLE
Add --fixtures-only option to generate fixtures without performing updates

### LINKED ISSUE #37: Add option to just generate a .fixtures file and not update the versions in the Modulefile
https://github.com/rnelson0/puppet-generate-puppetfile/pull/36 looks great!

But... it'd be nice if it were possible to generate the .fixtures file _without_ updating all the versions in the Puppetfile first.

Maybe this could be configurable, or even interactive (yes/no) style to each update being proposed.

### PR DESCRIPTION
**Pull request by rnelson0**
Fixes #37

### CODE REVIEW

**Comment by rnelson0** [comment]
@alexjfisher Let me know if this patch satisfies your need.

**Comment by alexjfisher** [comment]
The versions of the forge modules in the source Puppetfile don't make it to the .fixtures file generated.
Being able to test against the latest versions is nice, but I want to test roles against the exact contents of my Puppetfile.  Modules from git are ignored completely.  I was looking for a tool that allows me to 'sync' my .fixtures from a Puppetfile.  Maybe a better solution would be if Puppetlabs spec helper could just work with Puppetfiles instead?

**Comment by rnelson0** [comment]
@alexjfisher I've taken care of spacing issues between the module name and the version number. I don't have any really complex Puppetfiles to test with, but please confirm this works for you before I rebase/merge. Thanks!

**Comment by alexjfisher** [comment]
That looks much better for forge modules.  What was the verdict with regards modules from git?

**Comment by rnelson0** [comment]
Currently, no support. Tim is going to put in a request to support fixtures from git. I do not know when I will be able to get to it, definitely welcoming of PRs for that.

**Pull request merged**
